providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
      #  file:
      #    directory: '/providers'
      #    watch: true

#api:
#  insecure: true

accessLog:
  filePath: "/traefik_access.log"

  #log:
  #  level: DEBUG
  #  filePath: "/err.log"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http3: {}

certificatesResolvers:
  letsEncrypt:
    acme:
#      email: CHANGEME@CHANGE.CHANGEME
        #      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web

